config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  get "about", to: "home#about", as: "about"
  get "errors/not_found"
  get "errors/internal_server_error"
  get "home/index"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :carts, only: [ :index ]

  resources :orders, only: [ :index, :create, :show, :destroy ] do
    collection do
      get "order_requests", to: "orders#order_requests", as: "order_requests"
      get "checkout", to: "orders#checkout", as: "checkout"
      post "save_address", to: "orders#save_address", as: "save_address"
      get "payment", to: "orders#payment_page", as: "payment"
    end
    member do
      post "dispatch", to: "orders#approve", as: "dispatch"
      post "cancel", to: "orders#seller_cancel", as: "seller_cancel"
    end
  end

  resources :line_items, only: [ :create, :update, :destroy ]

  resources :users, only: [ :show, :edit, :update ]

  resources :products, only: [ :new, :index, :show, :destroy, :create, :update, :edit ] do
    collection do
      get "search_products", to: "products#search", as: "search"
    end
  end

  resources :sellers, only: [ :index ]

  resources :addresses, only: [ :index, :edit, :create, :update, :destroy, :show, :new ]

  resources :admins, only: [ :index ] do
    collection do
      get "all_products", to: "admins#all_products", as: "products"
    end
  end

  root "products#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :admin
    end

    if user.customer?
      can [ :index, :show, :create, :new, :update, :destroy ], :product
      can [ :index, :show, :payment_page, :checkout, :create, :destroy ], :order
      can :manage, :line_item
      can :manage, :cart
      can :manage, :address
    end

    if user.seller?
      can :manage, :seller
      can [ :order_requests, :approve, :seller_cancel ], :order
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  validates :shipping_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :zip_code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    validates :name, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart, optional: true
  belongs_to :order, optional: true
  belongs_to :product
  validates :quantity, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :cart_id, presence: false
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :line_items
  validates :total_price, presence: true, numericality: { greater_than: 0 }
  validates :status, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  include Discard::Model
  searchkick callbacks: :async
  after_discard :reindex
  has_one_attached :img
  has_many :line_items, dependent: :destroy

  validates :name, presence: { message: "must be present" }, uniqueness: { message: "must be unique" }
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :stock_quantity, presence: true
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"
  belongs_to :category

  def search_data
    return {} if discarded?
    {
      name: name,
      description: description,
      price: price,
      stock_quantity: stock_quantity,
      category_id: category_id,
      seller_id: seller_id
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :orders
    has_many :products, foreign_key: "seller_id", dependent: :destroy
    has_many :addresses, foreign_key: "user_id", dependent: :destroy
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
    has_one :cart, dependent: :destroy

    after_create :create_cart_for_user, if: -> { role == "user" }
    private
    def create_cart_for_user
        Cart.create!(user: self)
    end

    enum role: { admin: 0, customer: 1, seller: 2 }

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :phone_number, presence: true
    validates :role, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  authorize_resource class: false

  def index
    set_cart_and_items
  end

  def checkout
    redirect_to orders_path
  end

  private

  def set_cart_and_items
    @cart = Cart.find_by(user_id: current_user.id)
    @line_items = @cart.line_items.includes(:product) if @cart
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_carts.html.erb
<div class="cart">
  <h2>Your Cart</h2>
  <%= stylesheet_link_tag "mini_cart",media:'all' %>
  <% if @line_items %>
    <ul>
      <% @line_items.each do |line_item| %>
        <li>
          <%= image_tag line_item.product.img, width: 50, height: 50 %>
          <%= line_item.product.name %> - Quantity: <%= line_item.quantity %>
          <br>
          Price: <%= line_item.product.price %>
<%= button_to 'Remove', line_item_path(line_item), method: :delete, class:'btn btn-danger' %>

        </li>
      <% end %>
    </ul>
    <p>Total: <%= number_to_currency(@line_items.sum { |li| li.price * li.quantity }, unit: '₹', format: '%u%n', delimiter: ',', precision: 2) %></p>
    
    <div class="checkout-container">
    <% if @line_items.any? %>
<%= button_to 'Checkout', checkout_orders_path, method: :get, class: 'btn btn-primary ml-5' %>
<% end %>
    </div>
        <br>

  <% else %>
    <p>Your cart is empty.</p>
  <% end %>
</div>

app/views/carts/index.html.erb
<!-- app/views/carts/show.html.erb -->

<h1 class="text-center mb-4">Your Cart</h1>

<% if @line_items.any? %>
  <ul class="list-group">
    <% @line_items.each do |line_item| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <%= image_tag line_item.product.img, style: "width: 150px; height: 150px; object-fit: contain;", class: "me-3 rounded-circle" %>
          <div>
            <h5 class="mb-1"><%= line_item.product.name %></h5>
            <small>Quantity: <%= line_item.quantity %></small><br />
            <small>Price: <%= number_to_currency(line_item.product.price,unit:'₹') %></small>
          </div>
        </div>
        <%= button_to 'Remove', line_item_path(line_item), method: :delete, class:'btn btn-danger' %>
      </li>
    <% end %>
  </ul>
    <div class="text-center mt-3">
    <% if @line_items.any? %>
      <%= button_to 'Checkout', checkout_orders_path, method: :get, class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="text-center mt-3">
    <%= link_to 'Continue Shopping', products_path, class: 'btn btn-primary' %>
  </div>

<% else %>
  <div class="alert alert-warning text-center" role="alert">
    Your cart is currently empty.
  </div>
<% end %>