config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  get "about", to: "home#about", as: "about"
  get "errors/not_found"
  get "errors/internal_server_error"
  get "home/index"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :carts, only: [ :index ]

  resources :orders, only: [ :index, :create, :show, :destroy ] do
    collection do
      get "order_requests", to: "orders#order_requests", as: "order_requests"
      get "checkout", to: "orders#checkout", as: "checkout"
      post "save_address", to: "orders#save_address", as: "save_address"
      get "payment", to: "orders#payment_page", as: "payment"
    end
    member do
      post "dispatch", to: "orders#approve", as: "dispatch"
      post "cancel", to: "orders#seller_cancel", as: "seller_cancel"
    end
  end

  resources :line_items, only: [ :create, :update, :destroy ]

  resources :users, only: [ :show, :edit, :update ]

  resources :products, only: [ :new, :index, :show, :destroy, :create, :update, :edit ] do
    collection do
      get "search_products", to: "products#search", as: "search"
    end
  end

  resources :sellers, only: [ :index ]

  resources :addresses, only: [ :index, :edit, :create, :update, :destroy, :show, :new ]

  resources :admins, only: [ :index ] do
    collection do
      get "all_products", to: "admins#all_products", as: "products"
    end
  end

  root "products#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :admin
    end

    if user.customer?
      can [ :index, :show, :create, :new, :update, :destroy ], :product
      can [ :index, :show, :payment_page, :checkout, :create, :destroy ], :order
      can :manage, :line_item
      can :manage, :cart
      can :manage, :address
    end

    if user.seller?
      can :manage, :seller
      can [ :order_requests, :approve, :seller_cancel ], :order
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  validates :shipping_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :zip_code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    validates :name, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart, optional: true
  belongs_to :order, optional: true
  belongs_to :product
  validates :quantity, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :cart_id, presence: false
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :line_items
  validates :total_price, presence: true, numericality: { greater_than: 0 }
  validates :status, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  include Discard::Model
  searchkick callbacks: :async
  after_discard :reindex
  has_one_attached :img
  has_many :line_items, dependent: :destroy

  validates :name, presence: { message: "must be present" }, uniqueness: { message: "must be unique" }
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :stock_quantity, presence: true
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"
  belongs_to :category

  def search_data
    return {} if discarded?
    {
      name: name,
      description: description,
      price: price,
      stock_quantity: stock_quantity,
      category_id: category_id,
      seller_id: seller_id
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :orders
    has_many :products, foreign_key: "seller_id", dependent: :destroy
    has_many :addresses, foreign_key: "user_id", dependent: :destroy
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
    has_one :cart, dependent: :destroy

    after_create :create_cart_for_user, if: -> { role == "user" }
    private
    def create_cart_for_user
        Cart.create!(user: self)
    end

    enum role: { admin: 0, customer: 1, seller: 2 }

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :phone_number, presence: true
    validates :role, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    query = params[:query].presence || "*"
    conditions = {}
    conditions[:category_id] = params[:category_id] if params[:category_id].present?
    conditions[:seller_id] = params[:seller_id] if params[:seller_id].present?
    conditions[:seller_id] = current_user.id if conditions[:seller_id].nil? && current_user&.seller?
    @seller=User.find(conditions[:seller_id]) if conditions[:seller_id].present?
    sort_option = (params[:sort] == "desc" ? { price: :desc } : { price: :asc }) if params[:sort].present?
    if params[:clear]=="true"
      conditions={}
    end
    @products = Product.search(query, where: conditions, order: sort_option, page: params[:page], per_page: 8)
  end

  def show
    @product = Product.find(params[:id])
    @seller = @product.seller
    if current_user&.customer?
      @cart = Cart.find_by(user_id: current_user.id)
      @line_items = @cart.line_items.includes(:product)
    end
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path, notice: "Product was successfully updated."
    else
      @categories = Category.all
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.discard  # changed destroy to discarded
      flash.now[:notice] = "Product successfully deleted."
      redirect_to products_path
    else
      flash.now[:alert] = "Error deleting the product."
      render :show
    end
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash.now[:notice] = "Product created successfully!"
      redirect_to products_path
    else
      flash.now[:alert] = "There was a problem creating the product."
      redirect_to new_product_path
    end
  end


  # def seller_products
  #   @seller=User.find(params[:id])
  #   @products=@seller.products
  # end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :img, :stock_quantity, :category_id).merge(seller_id: current_user.id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_search_bar.html.erb
<div class="mb-4 mt-4 mr-5">
    <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search products..." %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
</div>

app/views/products/edit.html.erb
<%= form_with(model: @product, method: :patch, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :category_id, "Category" %>
    <%= form.select :category_id, @categories.map { |category| [category.name, category.id] }, { prompt: 'Select Category' }, class: "form-control", required: true %>
  </div>
  
  <div class="form-group">
    <%= form.label :name, "Product Name" %>
    <%= form.text_field :name, class: "form-control", value: @product.name %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Description" %>
    <%= form.text_area :description, class: "form-control", value: @product.description %>
  </div>

  <div class="form-group">
    <%= form.label :price, "Price" %>
    <%= form.number_field :price, step: 0.01, class: "form-control", value: @product.price %>
  </div>

  <div class="form-group">
    <%= form.label :img, "Image" %>
    <%= form.file_field :img, class: "form-control" %> 
  </div>

  <div class="form-group">
    <%= form.label :stock_quantity, "Stock Quantity" %>
    <%= form.number_field :stock_quantity, class: "form-control", value: @product.stock_quantity %>
  </div>

  <%= form.submit "Update Product", class: "btn btn-primary" %>
<% end %>

app/views/products/index.html.erb
<%= stylesheet_link_tag "products_index", media: "all" %>
<% if @seller.present? %>
<div class="mt-5">
  <h2>Products by
    <%= @seller.first_name + " " + @seller.last_name %></h2>
<% end %>
</div>
<div class="mb-4 mr-4 d-flex justify-content-end align-items-center">
  <%= form_with(url: products_path(category_id: :category_id,sort: :sort), method: :get, local: true, class: "form-inline") do %>
    <div class="form-group mr-2">
      <%= render "products/search_bar" %>
          <%= hidden_field_tag :seller_id, params[:seller_id]%>

      <%= select_tag :category_id,
      options_for_select(Category.all.pluck(:name, :id), params[:category_id]),
      include_blank: "Select Category",
      class: "form-control" %>
    </div>
    <div class="form-group mr-2">
      <%= select_tag :sort,
      options_for_select(
        [["Low to High", "asc"], ["High to Low", "desc"]],
        params[:sort],
      ),
      include_blank: "Sort by Price",
      class: "form-control" %>
    </div>
    <%= button_tag "Filter", type: "submit", class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Clear",
  products_path(clear: :true),
  method: :get,
  class: "btn btn-danger ml-3" %>

</div>
<% if !@products.present? and params[:query].present? %>
  <p class="text-center">No products found matching your search criteria.</p>
<% elsif !@products.present? and !params[:query].present? %>
  <p class="text-center">No products to show.</p>

<% else %>
  <div class="row">
    <% @products.each do |product| %>
    <% if product.kept? %>
      <div class="col-md-3 mb-4">
        <div class="card h-100">
          <% if product.img.attached? %>

          <%= image_tag url_for(product.img),
          class: "card-img-top",
          alt: product.name,
          style: "object-fit: contain; height: 200px;" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to product.name, product_path(product), class: "stretched-link" %>
            </h5>
            <p class="card-text">
              Price:
              <%= number_to_currency(
                product.price,
                unit: "₹",
                format: "%u%n",
                delimiter: ",",
                precision: 2,
              ) %>
            </p>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>

<div class="pagination-container">
  <%= paginate @products %>
</div>
<% end %>

app/views/products/new.html.erb
<%= form_with(model: @product, method: :post, local: true) do |form| %>
  <div class="container mt-4">
    <h2>Add New Product</h2>

    <div class="form-group">
      <%= form.label :category_id, "Category", class: "form-label" %>
      <%= form.collection_select :category_id,
                             @categories,
                             :id,
                             :name,
                             { prompt: "Select a Category" },
                             class: "form-control",
                             required: true %>
    </div>

    <div class="form-group">
      <%= form.label :name, "Product Name", class: "form-label" %>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :description, "Description", class: "form-label" %>
      <%= form.text_area :description, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :price, "Price", class: "form-label" %>
      <%= form.number_field :price, step: 0.01,min: 1, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :img, "Image", class: "form-label" %>
      <%= form.file_field :img, class: "form-control",accept: "image/jpeg,image/png", required: true %>
    </div>

    <div class="form-group">
      <%= form.label :stock_quantity, "Stock Quantity", class: "form-label" %>
      <%= form.number_field :stock_quantity, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= form.submit "Add Product", class: "btn btn-primary", required: true %>
    </div>
  </div>
<% end %>

app/views/products/seller_products.html.erb
<h1 class="text-center mb-4">Products by <%= @seller.first_name+" "+@seller.last_name %></h1>

<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100">
          <%= image_tag product.img, class: "card-img-top", alt: product.name, style: "object-fit: contain; height: 200px;" %>
          <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>
            <p class="card-text">
              <strong>Price:</strong> <%= number_to_currency(product.price, unit: '₹', format: '%u%n', delimiter: ',', precision: 2) %><br>
              <strong>Description:</strong> <%= truncate(product.description, length: 100) %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
 <%= stylesheet_link_tag 'products_show', media: 'all', data: { turbolinks: false } %> 
<div class="container mt-4">
  <div class="row">
  <% if @cart %>
    <div class="col-md-8">
    <% else %>
        <div class="col" style="width: 500px;"> 

    <% end %>
      <div class="card mb-4">
        <div class="card-header">
          <h1 class="h4"><%= @product.name %></h1>
        </div>
        <div class="card-body text-center">
                    <% if @product.img.attached? %>

<%= image_tag @product.img, class: 'img-fluid', style: 'max-width: 200px;', alt: @product.name %>
<% end %>
          <p class="mt-3"><%= @product.description %></p>
          <p class="h5">Price: <%= number_to_currency(@product.price, unit: '₹', format: '%u%n', delimiter: ',', precision: 2) %></p>
          <% if !current_user&.seller? %>
          <p class="h5">Sold by : <%= link_to @seller.first_name+" "+@seller.last_name ,products_path("seller_id": @seller.id)%></p>
          <% end %>
          <% if @product.stock_quantity<=0 %>
          <h4>Out of stock</h4>
          <% else %>
          <p class="h5">Stock : <%= @product.stock_quantity %></p>
          <% end %>
          <% if current_user.nil? %>
          <%= link_to 'Login for shopping' , new_user_session_path, class:"btn btn-danger" %>
          <% end %>
        </div>

        <% if @cart %>
        <div class="card-footer">
          <!-- Form for adding to cart -->
          <%= form_with url: line_items_path, method: :post, local: true do %>
            <div class="input-group mb-3">
              <select name="line_item[quantity]" class="form-select form-select-sm" style="margin-top: 10px" aria-label="Select quantity">
                <% (1..5).each do |num| %>
                  <option value="<%= num %>"><%= num %></option>
                <% end %>   
              </select>
              <% if @product.stock_quantity>0 %>
              <%= button_tag 'Add to Cart', type: 'submit', class: 'btn btn-primary' %>
              <% else %>
              <%= button_tag 'Add to Cart', type: 'submit', class: 'btn btn-primary',disabled:true %>
              <% end %>

            </div>
            <%= hidden_field_tag 'line_item[product_id]', @product.id %>
            <%= hidden_field_tag 'line_item[cart_id]', session[:cart_id] %>
            <%= hidden_field_tag 'line_item[order_id]', nil %>
            <%= hidden_field_tag 'line_item[price]', @product.price %>
            <%= hidden_field_tag 'line_item[status]', 'pending' %>
            
          <% end %>
        </div>
      </div>
    </div>

    <% end %>
  <% if @cart %>
    <div class="col-md-4"> 
      <div style="position: sticky; top: 20px;">
        <%= render 'carts/carts' %> 
      </div>
    </div>
  </div>
</div>



<% else %>

<% if current_user&.seller? && @product.seller == current_user %>
  <div class="text-center">
    <%= button_to "Remove Item", product_path(@product.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
    <br>
    <%= button_to "Update Item", edit_product_path(@product.id), method: :get, class: 'btn btn-danger' %>
  </div>
<% end %>


<% end %>