config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  get "about", to: "home#about", as: "about"
  get "errors/not_found"
  get "errors/internal_server_error"
  get "home/index"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :carts, only: [ :index ]

  resources :orders, only: [ :index, :create, :show, :destroy ] do
    collection do
      get "order_requests", to: "orders#order_requests", as: "order_requests"
      get "checkout", to: "orders#checkout", as: "checkout"
      post "save_address", to: "orders#save_address", as: "save_address"
      get "payment", to: "orders#payment_page", as: "payment"
    end
    member do
      post "dispatch", to: "orders#approve", as: "dispatch"
      post "cancel", to: "orders#seller_cancel", as: "seller_cancel"
    end
  end

  resources :line_items, only: [ :create, :update, :destroy ]

  resources :users, only: [ :show, :edit, :update ]

  resources :products, only: [ :new, :index, :show, :destroy, :create, :update, :edit ] do
    collection do
      get "search_products", to: "products#search", as: "search"
    end
  end

  resources :sellers, only: [ :index ]

  resources :addresses, only: [ :index, :edit, :create, :update, :destroy, :show, :new ]

  resources :admins, only: [ :index ] do
    collection do
      get "all_products", to: "admins#all_products", as: "products"
    end
  end

  root "products#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :admin
    end

    if user.customer?
      can [ :index, :show, :create, :new, :update, :destroy ], :product
      can [ :index, :show, :payment_page, :checkout, :create, :destroy ], :order
      can :manage, :line_item
      can :manage, :cart
      can :manage, :address
    end

    if user.seller?
      can :manage, :seller
      can [ :order_requests, :approve, :seller_cancel ], :order
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  validates :shipping_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :zip_code, presence: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    validates :name, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart, optional: true
  belongs_to :order, optional: true
  belongs_to :product
  validates :quantity, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :cart_id, presence: false
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :line_items
  validates :total_price, presence: true, numericality: { greater_than: 0 }
  validates :status, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  include Discard::Model
  searchkick callbacks: :async
  after_discard :reindex
  has_one_attached :img
  has_many :line_items, dependent: :destroy

  validates :name, presence: { message: "must be present" }, uniqueness: { message: "must be unique" }
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :stock_quantity, presence: true
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"
  belongs_to :category

  def search_data
    return {} if discarded?
    {
      name: name,
      description: description,
      price: price,
      stock_quantity: stock_quantity,
      category_id: category_id,
      seller_id: seller_id
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :orders
    has_many :products, foreign_key: "seller_id", dependent: :destroy
    has_many :addresses, foreign_key: "user_id", dependent: :destroy
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
    has_one :cart, dependent: :destroy

    after_create :create_cart_for_user, if: -> { role == "user" }
    private
    def create_cart_for_user
        Cart.create!(user: self)
    end

    enum role: { admin: 0, customer: 1, seller: 2 }

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :phone_number, presence: true
    validates :role, presence: true
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/all_products.html.erb
<div class="container mt-4">
  <%= stylesheet_link_tag 'pagination', media:"all" %>

  <h2>Product List</h2>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead class="table-dark">
        <tr>
          <th>Product Name</th>
          <th>Quantity</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.stock_quantity %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
        <div class="pagination-container">
  <%= paginate @products %>
</div>  
  </div>
</div>

app/views/admins/index.html.erb
<div class="container my-4">
  <%= stylesheet_link_tag 'pagination', media:"all" %>
  <h2>Order List</h2>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Order ID</th>
          <th scope="col">Order Date</th>
          <th scope="col">Total Amount</th>
          <th scope="col">Status</th>
        </tr>
      </thead>    
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= order.id %></td>
            <td><%= order.created_at.strftime("%Y-%m-%d") %></td>
            <td><%= number_to_currency(order.total_price,unit:"₹", format: '%u%n', delimiter: ',', precision: 2) %></td>
            <td>
              <% if order.status=="Partial" %>
              <span class="badge">
              <%= "#{order.line_items.count { |line_item| line_item.status == 'Dispatched' }} / #{order.line_items.count} Confirmed" %>
              </span>
              <% else %>
              <span class="badge">
              <%= order.status.capitalize %>
              </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="pagination-container">
  <%= paginate @orders %>
</div>
  </div>
</div>

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= key == 'alert' ? 'alert-danger' : 'alert-success' %> flash-message" style="ml-5;" >
    <%= message %>
  </div>
<% end %> 

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const flashMessages = document.querySelectorAll('.flash-message');

    flashMessages.forEach(function(message) {
      setTimeout(function() {
        message.style.opacity = 0; // Fade out
        setTimeout(function() {
          message.remove();
        }, 500); 
      }, 3000); 
    });
  });
</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <%= link_to 'iBuy', about_path, class: "navbar-brand" %>
  <%= stylesheet_link_tag "navbar", media: "all" %>


  <div class="collapse navbar-collapse" id="navbarSupportedContent" style='margin-top:5px;'>
    <ul class="navbar-nav mr-auto">
      <% unless current_user&.admin? %>
        <li class="nav-item <%= 'active' if current_page?(products_path) %>">
          <%= link_to 'Products', products_path, class: "nav-link" %>
        </li>
        <% else%>
          <li class="nav-item <%= 'active' if current_page?(products_path) %>">
          <%= link_to 'Products', products_admins_path, class: "nav-link" %>
        </li>
          <li class="nav-item <%= 'active' if current_page?(products_path) %>">
          <%= link_to 'Orders', admins_path, class: "nav-link" %>
        </li>
      <% end %>
      <% if current_user.nil? %>
      <li class="nav-item <%= 'active' if current_page?(new_user_session_path) %>">
        <%= link_to 'Login', new_user_session_path, class: "nav-link" %> 
      </li>
      <% end %>
    </ul>

    <ul class="navbar-nav ml-auto"> 
      <li class="nav-item d-flex align-items-center"> 
        <% if current_user %>

        <% if current_user&.customer? %>
          <%= link_to image_tag("cart.jpeg", class: "logo"), carts_path, class: "nav-link" %>
          <%= link_to 'Sellers', sellers_path, class: "nav-link ms-3" %> 
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %> 
          <%= link_to 'Orders', orders_path, class: "nav-link" %>

        <% elsif current_user.seller? %>
          <%= link_to 'Add New Product', new_product_path, class: 'nav-link' %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %> 
          <%= link_to 'Order List', order_requests_orders_path, class: "nav-link" %>
          <% elsif current_user.admin? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %> 

        <% end %> 
          </li>
          <li class="nav-item d-flex align-items-center">
          <%= link_to "#{current_user.role.capitalize} Profile", user_path(current_user.id), class: "nav-link" %>
          </li>
        </ul>

        <% else %>

        <h6 class="nav-link mt-2">Guest</h6>
<% end %>
  </div>
</nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>iBuy</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

</head>
<body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<%= render 'layouts/navbar' %>
<%= render 'layouts/flash_message'%>

  <%= yield %>
</body>
</html>